sass:
  style: compressed

exclude: ['/bin/', 'README.md', 'CNAME', 'package.json', '/node_modules/', 'gulpfile.js', 'web-extrema.sublime-project', 'web-extrema.sublime-workspace', '/.git/', '.gitignore', 'extrema.yaml']